apiVersion: v1
kind: Service
metadata:
  name: beer-nrc-svc
spec:
  ports:
    - name: http
      port: 9090
  selector:
    app: beer-nrc
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: beer-nrc-client-svc
spec:
  ports:
    - name: http
      port: 3000
      nodePort: 30000
  selector:
    app: beer-nrc-client
  type: NodePort
